curl -o MMM.pdf -o ABT.pdf -o ABBV.pdf -o ACN.pdf -o AYI.pdf -o AAP.pdf -o AES.pdf -o AET.pdf -o AMG.pdf -o AFL.pdf -o A.pdf -o APD.pdf -o ALK.pdf -o ALB.pdf -o ARE.pdf -o ALLE.pdf -o AGN.pdf -o ADS.pdf -o LNT.pdf -o ALL.pdf -o MO.pdf -o AEE.pdf -o AEP.pdf -o AXP.pdf -o AIG.pdf -o AMT.pdf -o AWK.pdf -o AMP.pdf -o ABC.pdf -o AME.pdf -o APH.pdf -o APC.pdf -o ANDV.pdf -o ANTM.pdf -o AON.pdf -o AOS.pdf -o APA.pdf -o AIV.pdf -o APTV.pdf -o ADM.pdf -o ARNC.pdf -o AJG.pdf -o AIZ.pdf -o T.pdf -o AZO.pdf -o AVB.pdf -o AVY.pdf -o BHGE.pdf -o BLL.pdf -o BAC.pdf -o BK.pdf -o BAX.pdf -o BBT.pdf -o BDX.pdf -o BRK.B.pdf -o BBY.pdf -o BLK.pdf -o HRB.pdf -o BA.pdf -o BWA.pdf -o BXP.pdf -o BSX.pdf -o BMY.pdf -o BF.B.pdf -o COG.pdf -o CPB.pdf -o COF.pdf -o CAH.pdf -o KMX.pdf -o CCL.pdf -o CAT.pdf -o CBRE.pdf -o CBS.pdf -o CNC.pdf -o CNP.pdf -o CTL.pdf -o CF.pdf -o SCHW.pdf -o CVX.pdf -o CMG.pdf -o CB.pdf -o CHD.pdf -o CI.pdf -o XEC.pdf -o C.pdf -o CFG.pdf -o CLX.pdf -o CMS.pdf -o KO.pdf -o CL.pdf -o CMA.pdf -o CAG.pdf -o CXO.pdf -o COP.pdf -o ED.pdf -o STZ.pdf -o COO.pdf -o GLW.pdf -o COTY.pdf -o CCI.pdf -o CMI.pdf -o CVS.pdf -o DHI.pdf -o DHR.pdf -o DRI.pdf -o DVA.pdf -o DE.pdf -o DAL.pdf -o DVN.pdf -o DLR.pdf -o DFS.pdf -o DG.pdf -o D.pdf -o DOV.pdf -o DWDP.pdf -o DPS.pdf -o DTE.pdf -o DRE.pdf -o DUK.pdf -o DXC.pdf -o EMN.pdf -o ETN.pdf -o ECL.pdf -o EIX.pdf -o EW.pdf -o EMR.pdf -o ETR.pdf -o EVHC.pdf -o EOG.pdf -o EQT.pdf -o EFX.pdf -o EQR.pdf -o ESS.pdf -o EL.pdf -o EVRG.pdf -o ES.pdf -o RE.pdf -o EXC.pdf -o EXR.pdf -o XOM.pdf -o FRT.pdf -o FDX.pdf -o FIS.pdf -o FE.pdf -o FLS.pdf -o FLR.pdf -o FMC.pdf -o FL.pdf -o F.pdf -o FTV.pdf -o FBHS.pdf -o BEN.pdf -o FCX.pdf -o GPS.pdf -o IT.pdf -o GD.pdf -o GE.pdf -o GGP.pdf -o GIS.pdf -o GM.pdf -o GPC.pdf -o GPN.pdf -o GS.pdf -o GWW.pdf -o HAL.pdf -o HBI.pdf -o HOG.pdf -o HRS.pdf -o HIG.pdf -o HCA.pdf -o HCP.pdf -o HP.pdf -o HSY.pdf -o HES.pdf -o HPE.pdf -o HLT.pdf -o HD.pdf -o HON.pdf -o HRL.pdf -o HST.pdf -o HPQ.pdf -o HUM.pdf -o HII.pdf -o ITW.pdf -o IR.pdf -o ICE.pdf -o IBM.pdf -o IP.pdf -o IPG.pdf -o IFF.pdf -o IVZ.pdf -o IQV.pdf -o IRM.pdf -o JEC.pdf -o JEF.pdf -o SJM.pdf -o JNJ.pdf -o JCI.pdf -o JPM.pdf -o JNPR.pdf -o KSU.pdf -o K.pdf -o KEY.pdf -o KMB.pdf -o KIM.pdf -o KMI.pdf -o KSS.pdf -o KR.pdf -o LB.pdf -o LLL.pdf -o LH.pdf -o LEG.pdf -o LEN.pdf -o LLY.pdf -o LNC.pdf -o LMT.pdf -o L.pdf -o LOW.pdf -o LYB.pdf -o MTB.pdf -o MAC.pdf -o M.pdf -o MRO.pdf -o MPC.pdf -o MMC.pdf -o MLM.pdf -o MAS.pdf -o MA.pdf -o MKC.pdf -o MCD.pdf -o MCK.pdf -o MDT.pdf -o MRK.pdf -o MET.pdf -o MTD.pdf -o MGM.pdf -o KORS.pdf -o MAA.pdf -o MHK.pdf -o TAP.pdf -o MCO.pdf -o MS.pdf -o MOS.pdf -o MSI.pdf -o MSCI.pdf -o NOV.pdf -o NWL.pdf -o NFX.pdf -o NEM.pdf -o NEE.pdf -o NLSN.pdf -o NKE.pdf -o NI.pdf -o NBL.pdf -o JWN.pdf -o NSC.pdf -o NOC.pdf -o NCLH.pdf -o NRG.pdf -o NUE.pdf -o OXY.pdf -o OMC.pdf -o OKE.pdf -o ORCL.pdf -o PKG.pdf -o PH.pdf -o PNR.pdf -o PKI.pdf -o PRGO.pdf -o PFE.pdf -o PCG.pdf -o PM.pdf -o PSX.pdf -o PNW.pdf -o PXD.pdf -o PNC.pdf -o RL.pdf -o PPG.pdf -o PPL.pdf -o PX.pdf -o PG.pdf -o PGR.pdf -o PLD.pdf -o PRU.pdf -o PEG.pdf -o PSA.pdf -o PHM.pdf -o PVH.pdf -o PWR.pdf -o DGX.pdf -o RRC.pdf -o RJF.pdf -o RTN.pdf -o O.pdf -o RHT.pdf -o REG.pdf -o RF.pdf -o RSG.pdf -o RMD.pdf -o RHI.pdf -o ROK.pdf -o COL.pdf -o ROP.pdf -o RCL.pdf -o CRM.pdf -o SCG.pdf -o SLB.pdf -o SEE.pdf -o SRE.pdf -o SHW.pdf -o SPG.pdf -o SLG.pdf -o SNA.pdf -o SO.pdf -o LUV.pdf -o SPGI.pdf -o SWK.pdf -o STT.pdf -o SYK.pdf -o STI.pdf -o SYF.pdf -o SYY.pdf -o TPR.pdf -o TGT.pdf -o TEL.pdf -o FTI.pdf -o TXT.pdf -o TMO.pdf -o TIF.pdf -o TWTR.pdf -o TWX.pdf -o TJX.pdf -o TMK.pdf -o TSS.pdf -o TDG.pdf -o TRV.pdf -o TSN.pdf -o UDR.pdf -o USB.pdf -o UAA.pdf -o UA.pdf -o UNP.pdf -o UAL.pdf -o UNH.pdf -o UPS.pdf -o URI.pdf -o UTX.pdf -o UHS.pdf -o UNM.pdf -o VFC.pdf -o VLO.pdf -o VAR.pdf -o VTR.pdf -o VZ.pdf -o V.pdf -o VNO.pdf -o VMC.pdf -o WMT.pdf -o DIS.pdf -o WM.pdf -o WAT.pdf -o WEC.pdf -o WFC.pdf -o WELL.pdf -o WU.pdf -o WRK.pdf -o WY.pdf -o WHR.pdf -o WMB.pdf -o XRX.pdf -o XL.pdf -o XYL.pdf -o YUM.pdf -o ZBH.pdf -o ZTS.pdf http://quotes.morningstar.com/stock/analysis-report?t=Xnys:{MMM,ABT,ABBV,ACN,AYI,AAP,AES,AET,AMG,AFL,A,APD,ALK,ALB,ARE,ALLE,AGN,ADS,LNT,ALL,MO,AEE,AEP,AXP,AIG,AMT,AWK,AMP,ABC,AME,APH,APC,ANDV,ANTM,AON,AOS,APA,AIV,APTV,ADM,ARNC,AJG,AIZ,T,AZO,AVB,AVY,BHGE,BLL,BAC,BK,BAX,BBT,BDX,BRK.B,BBY,BLK,HRB,BA,BWA,BXP,BSX,BMY,BF.B,COG,CPB,COF,CAH,KMX,CCL,CAT,CBRE,CBS,CNC,CNP,CTL,CF,SCHW,CVX,CMG,CB,CHD,CI,XEC,C,CFG,CLX,CMS,KO,CL,CMA,CAG,CXO,COP,ED,STZ,COO,GLW,COTY,CCI,CMI,CVS,DHI,DHR,DRI,DVA,DE,DAL,DVN,DLR,DFS,DG,D,DOV,DWDP,DPS,DTE,DRE,DUK,DXC,EMN,ETN,ECL,EIX,EW,EMR,ETR,EVHC,EOG,EQT,EFX,EQR,ESS,EL,EVRG,ES,RE,EXC,EXR,XOM,FRT,FDX,FIS,FE,FLS,FLR,FMC,FL,F,FTV,FBHS,BEN,FCX,GPS,IT,GD,GE,GGP,GIS,GM,GPC,GPN,GS,GWW,HAL,HBI,HOG,HRS,HIG,HCA,HCP,HP,HSY,HES,HPE,HLT,HD,HON,HRL,HST,HPQ,HUM,HII,ITW,IR,ICE,IBM,IP,IPG,IFF,IVZ,IQV,IRM,JEC,JEF,SJM,JNJ,JCI,JPM,JNPR,KSU,K,KEY,KMB,KIM,KMI,KSS,KR,LB,LLL,LH,LEG,LEN,LLY,LNC,LMT,L,LOW,LYB,MTB,MAC,M,MRO,MPC,MMC,MLM,MAS,MA,MKC,MCD,MCK,MDT,MRK,MET,MTD,MGM,KORS,MAA,MHK,TAP,MCO,MS,MOS,MSI,MSCI,NOV,NWL,NFX,NEM,NEE,NLSN,NKE,NI,NBL,JWN,NSC,NOC,NCLH,NRG,NUE,OXY,OMC,OKE,ORCL,PKG,PH,PNR,PKI,PRGO,PFE,PCG,PM,PSX,PNW,PXD,PNC,RL,PPG,PPL,PX,PG,PGR,PLD,PRU,PEG,PSA,PHM,PVH,PWR,DGX,RRC,RJF,RTN,O,RHT,REG,RF,RSG,RMD,RHI,ROK,COL,ROP,RCL,CRM,SCG,SLB,SEE,SRE,SHW,SPG,SLG,SNA,SO,LUV,SPGI,SWK,STT,SYK,STI,SYF,SYY,TPR,TGT,TEL,FTI,TXT,TMO,TIF,TWTR,TWX,TJX,TMK,TSS,TDG,TRV,TSN,UDR,USB,UAA,UA,UNP,UAL,UNH,UPS,URI,UTX,UHS,UNM,VFC,VLO,VAR,VTR,VZ,V,VNO,VMC,WMT,DIS,WM,WAT,WEC,WFC,WELL,WU,WRK,WY,WHR,WMB,XRX,XL,XYL,YUM}
pdftohtml -c -f 1 -l 1 MMM.pdf
pdftohtml -c -f 1 -l 1 ABT.pdf
pdftohtml -c -f 1 -l 1 ABBV.pdf
pdftohtml -c -f 1 -l 1 ACN.pdf
pdftohtml -c -f 1 -l 1 AYI.pdf
pdftohtml -c -f 1 -l 1 AAP.pdf
pdftohtml -c -f 1 -l 1 AES.pdf
pdftohtml -c -f 1 -l 1 AET.pdf
pdftohtml -c -f 1 -l 1 AMG.pdf
pdftohtml -c -f 1 -l 1 AFL.pdf
pdftohtml -c -f 1 -l 1 A.pdf
pdftohtml -c -f 1 -l 1 APD.pdf
pdftohtml -c -f 1 -l 1 ALK.pdf
pdftohtml -c -f 1 -l 1 ALB.pdf
pdftohtml -c -f 1 -l 1 ARE.pdf
pdftohtml -c -f 1 -l 1 ALLE.pdf
pdftohtml -c -f 1 -l 1 AGN.pdf
pdftohtml -c -f 1 -l 1 ADS.pdf
pdftohtml -c -f 1 -l 1 LNT.pdf
pdftohtml -c -f 1 -l 1 ALL.pdf
pdftohtml -c -f 1 -l 1 MO.pdf
pdftohtml -c -f 1 -l 1 AEE.pdf
pdftohtml -c -f 1 -l 1 AEP.pdf
pdftohtml -c -f 1 -l 1 AXP.pdf
pdftohtml -c -f 1 -l 1 AIG.pdf
pdftohtml -c -f 1 -l 1 AMT.pdf
pdftohtml -c -f 1 -l 1 AWK.pdf
pdftohtml -c -f 1 -l 1 AMP.pdf
pdftohtml -c -f 1 -l 1 ABC.pdf
pdftohtml -c -f 1 -l 1 AME.pdf
pdftohtml -c -f 1 -l 1 APH.pdf
pdftohtml -c -f 1 -l 1 APC.pdf
pdftohtml -c -f 1 -l 1 ANDV.pdf
pdftohtml -c -f 1 -l 1 ANTM.pdf
pdftohtml -c -f 1 -l 1 AON.pdf
pdftohtml -c -f 1 -l 1 AOS.pdf
pdftohtml -c -f 1 -l 1 APA.pdf
pdftohtml -c -f 1 -l 1 AIV.pdf
pdftohtml -c -f 1 -l 1 APTV.pdf
pdftohtml -c -f 1 -l 1 ADM.pdf
pdftohtml -c -f 1 -l 1 ARNC.pdf
pdftohtml -c -f 1 -l 1 AJG.pdf
pdftohtml -c -f 1 -l 1 AIZ.pdf
pdftohtml -c -f 1 -l 1 T.pdf
pdftohtml -c -f 1 -l 1 AZO.pdf
pdftohtml -c -f 1 -l 1 AVB.pdf
pdftohtml -c -f 1 -l 1 AVY.pdf
pdftohtml -c -f 1 -l 1 BHGE.pdf
pdftohtml -c -f 1 -l 1 BLL.pdf
pdftohtml -c -f 1 -l 1 BAC.pdf
pdftohtml -c -f 1 -l 1 BK.pdf
pdftohtml -c -f 1 -l 1 BAX.pdf
pdftohtml -c -f 1 -l 1 BBT.pdf
pdftohtml -c -f 1 -l 1 BDX.pdf
pdftohtml -c -f 1 -l 1 BRK.B.pdf
pdftohtml -c -f 1 -l 1 BBY.pdf
pdftohtml -c -f 1 -l 1 BLK.pdf
pdftohtml -c -f 1 -l 1 HRB.pdf
pdftohtml -c -f 1 -l 1 BA.pdf
pdftohtml -c -f 1 -l 1 BWA.pdf
pdftohtml -c -f 1 -l 1 BXP.pdf
pdftohtml -c -f 1 -l 1 BSX.pdf
pdftohtml -c -f 1 -l 1 BMY.pdf
pdftohtml -c -f 1 -l 1 BF.B.pdf
pdftohtml -c -f 1 -l 1 COG.pdf
pdftohtml -c -f 1 -l 1 CPB.pdf
pdftohtml -c -f 1 -l 1 COF.pdf
pdftohtml -c -f 1 -l 1 CAH.pdf
pdftohtml -c -f 1 -l 1 KMX.pdf
pdftohtml -c -f 1 -l 1 CCL.pdf
pdftohtml -c -f 1 -l 1 CAT.pdf
pdftohtml -c -f 1 -l 1 CBRE.pdf
pdftohtml -c -f 1 -l 1 CBS.pdf
pdftohtml -c -f 1 -l 1 CNC.pdf
pdftohtml -c -f 1 -l 1 CNP.pdf
pdftohtml -c -f 1 -l 1 CTL.pdf
pdftohtml -c -f 1 -l 1 CF.pdf
pdftohtml -c -f 1 -l 1 SCHW.pdf
pdftohtml -c -f 1 -l 1 CVX.pdf
pdftohtml -c -f 1 -l 1 CMG.pdf
pdftohtml -c -f 1 -l 1 CB.pdf
pdftohtml -c -f 1 -l 1 CHD.pdf
pdftohtml -c -f 1 -l 1 CI.pdf
pdftohtml -c -f 1 -l 1 XEC.pdf
pdftohtml -c -f 1 -l 1 C.pdf
pdftohtml -c -f 1 -l 1 CFG.pdf
pdftohtml -c -f 1 -l 1 CLX.pdf
pdftohtml -c -f 1 -l 1 CMS.pdf
pdftohtml -c -f 1 -l 1 KO.pdf
pdftohtml -c -f 1 -l 1 CL.pdf
pdftohtml -c -f 1 -l 1 CMA.pdf
pdftohtml -c -f 1 -l 1 CAG.pdf
pdftohtml -c -f 1 -l 1 CXO.pdf
pdftohtml -c -f 1 -l 1 COP.pdf
pdftohtml -c -f 1 -l 1 ED.pdf
pdftohtml -c -f 1 -l 1 STZ.pdf
pdftohtml -c -f 1 -l 1 COO.pdf
pdftohtml -c -f 1 -l 1 GLW.pdf
pdftohtml -c -f 1 -l 1 COTY.pdf
pdftohtml -c -f 1 -l 1 CCI.pdf
pdftohtml -c -f 1 -l 1 CMI.pdf
pdftohtml -c -f 1 -l 1 CVS.pdf
pdftohtml -c -f 1 -l 1 DHI.pdf
pdftohtml -c -f 1 -l 1 DHR.pdf
pdftohtml -c -f 1 -l 1 DRI.pdf
pdftohtml -c -f 1 -l 1 DVA.pdf
pdftohtml -c -f 1 -l 1 DE.pdf
pdftohtml -c -f 1 -l 1 DAL.pdf
pdftohtml -c -f 1 -l 1 DVN.pdf
pdftohtml -c -f 1 -l 1 DLR.pdf
pdftohtml -c -f 1 -l 1 DFS.pdf
pdftohtml -c -f 1 -l 1 DG.pdf
pdftohtml -c -f 1 -l 1 D.pdf
pdftohtml -c -f 1 -l 1 DOV.pdf
pdftohtml -c -f 1 -l 1 DWDP.pdf
pdftohtml -c -f 1 -l 1 DPS.pdf
pdftohtml -c -f 1 -l 1 DTE.pdf
pdftohtml -c -f 1 -l 1 DRE.pdf
pdftohtml -c -f 1 -l 1 DUK.pdf
pdftohtml -c -f 1 -l 1 DXC.pdf
pdftohtml -c -f 1 -l 1 EMN.pdf
pdftohtml -c -f 1 -l 1 ETN.pdf
pdftohtml -c -f 1 -l 1 ECL.pdf
pdftohtml -c -f 1 -l 1 EIX.pdf
pdftohtml -c -f 1 -l 1 EW.pdf
pdftohtml -c -f 1 -l 1 EMR.pdf
pdftohtml -c -f 1 -l 1 ETR.pdf
pdftohtml -c -f 1 -l 1 EVHC.pdf
pdftohtml -c -f 1 -l 1 EOG.pdf
pdftohtml -c -f 1 -l 1 EQT.pdf
pdftohtml -c -f 1 -l 1 EFX.pdf
pdftohtml -c -f 1 -l 1 EQR.pdf
pdftohtml -c -f 1 -l 1 ESS.pdf
pdftohtml -c -f 1 -l 1 EL.pdf
pdftohtml -c -f 1 -l 1 EVRG.pdf
pdftohtml -c -f 1 -l 1 ES.pdf
pdftohtml -c -f 1 -l 1 RE.pdf
pdftohtml -c -f 1 -l 1 EXC.pdf
pdftohtml -c -f 1 -l 1 EXR.pdf
pdftohtml -c -f 1 -l 1 XOM.pdf
pdftohtml -c -f 1 -l 1 FRT.pdf
pdftohtml -c -f 1 -l 1 FDX.pdf
pdftohtml -c -f 1 -l 1 FIS.pdf
pdftohtml -c -f 1 -l 1 FE.pdf
pdftohtml -c -f 1 -l 1 FLS.pdf
pdftohtml -c -f 1 -l 1 FLR.pdf
pdftohtml -c -f 1 -l 1 FMC.pdf
pdftohtml -c -f 1 -l 1 FL.pdf
pdftohtml -c -f 1 -l 1 F.pdf
pdftohtml -c -f 1 -l 1 FTV.pdf
pdftohtml -c -f 1 -l 1 FBHS.pdf
pdftohtml -c -f 1 -l 1 BEN.pdf
pdftohtml -c -f 1 -l 1 FCX.pdf
pdftohtml -c -f 1 -l 1 GPS.pdf
pdftohtml -c -f 1 -l 1 IT.pdf
pdftohtml -c -f 1 -l 1 GD.pdf
pdftohtml -c -f 1 -l 1 GE.pdf
pdftohtml -c -f 1 -l 1 GGP.pdf
pdftohtml -c -f 1 -l 1 GIS.pdf
pdftohtml -c -f 1 -l 1 GM.pdf
pdftohtml -c -f 1 -l 1 GPC.pdf
pdftohtml -c -f 1 -l 1 GPN.pdf
pdftohtml -c -f 1 -l 1 GS.pdf
pdftohtml -c -f 1 -l 1 GWW.pdf
pdftohtml -c -f 1 -l 1 HAL.pdf
pdftohtml -c -f 1 -l 1 HBI.pdf
pdftohtml -c -f 1 -l 1 HOG.pdf
pdftohtml -c -f 1 -l 1 HRS.pdf
pdftohtml -c -f 1 -l 1 HIG.pdf
pdftohtml -c -f 1 -l 1 HCA.pdf
pdftohtml -c -f 1 -l 1 HCP.pdf
pdftohtml -c -f 1 -l 1 HP.pdf
pdftohtml -c -f 1 -l 1 HSY.pdf
pdftohtml -c -f 1 -l 1 HES.pdf
pdftohtml -c -f 1 -l 1 HPE.pdf
pdftohtml -c -f 1 -l 1 HLT.pdf
pdftohtml -c -f 1 -l 1 HD.pdf
pdftohtml -c -f 1 -l 1 HON.pdf
pdftohtml -c -f 1 -l 1 HRL.pdf
pdftohtml -c -f 1 -l 1 HST.pdf
pdftohtml -c -f 1 -l 1 HPQ.pdf
pdftohtml -c -f 1 -l 1 HUM.pdf
pdftohtml -c -f 1 -l 1 HII.pdf
pdftohtml -c -f 1 -l 1 ITW.pdf
pdftohtml -c -f 1 -l 1 IR.pdf
pdftohtml -c -f 1 -l 1 ICE.pdf
pdftohtml -c -f 1 -l 1 IBM.pdf
pdftohtml -c -f 1 -l 1 IP.pdf
pdftohtml -c -f 1 -l 1 IPG.pdf
pdftohtml -c -f 1 -l 1 IFF.pdf
pdftohtml -c -f 1 -l 1 IVZ.pdf
pdftohtml -c -f 1 -l 1 IQV.pdf
pdftohtml -c -f 1 -l 1 IRM.pdf
pdftohtml -c -f 1 -l 1 JEC.pdf
pdftohtml -c -f 1 -l 1 JEF.pdf
pdftohtml -c -f 1 -l 1 SJM.pdf
pdftohtml -c -f 1 -l 1 JNJ.pdf
pdftohtml -c -f 1 -l 1 JCI.pdf
pdftohtml -c -f 1 -l 1 JPM.pdf
pdftohtml -c -f 1 -l 1 JNPR.pdf
pdftohtml -c -f 1 -l 1 KSU.pdf
pdftohtml -c -f 1 -l 1 K.pdf
pdftohtml -c -f 1 -l 1 KEY.pdf
pdftohtml -c -f 1 -l 1 KMB.pdf
pdftohtml -c -f 1 -l 1 KIM.pdf
pdftohtml -c -f 1 -l 1 KMI.pdf
pdftohtml -c -f 1 -l 1 KSS.pdf
pdftohtml -c -f 1 -l 1 KR.pdf
pdftohtml -c -f 1 -l 1 LB.pdf
pdftohtml -c -f 1 -l 1 LLL.pdf
pdftohtml -c -f 1 -l 1 LH.pdf
pdftohtml -c -f 1 -l 1 LEG.pdf
pdftohtml -c -f 1 -l 1 LEN.pdf
pdftohtml -c -f 1 -l 1 LLY.pdf
pdftohtml -c -f 1 -l 1 LNC.pdf
pdftohtml -c -f 1 -l 1 LMT.pdf
pdftohtml -c -f 1 -l 1 L.pdf
pdftohtml -c -f 1 -l 1 LOW.pdf
pdftohtml -c -f 1 -l 1 LYB.pdf
pdftohtml -c -f 1 -l 1 MTB.pdf
pdftohtml -c -f 1 -l 1 MAC.pdf
pdftohtml -c -f 1 -l 1 M.pdf
pdftohtml -c -f 1 -l 1 MRO.pdf
pdftohtml -c -f 1 -l 1 MPC.pdf
pdftohtml -c -f 1 -l 1 MMC.pdf
pdftohtml -c -f 1 -l 1 MLM.pdf
pdftohtml -c -f 1 -l 1 MAS.pdf
pdftohtml -c -f 1 -l 1 MA.pdf
pdftohtml -c -f 1 -l 1 MKC.pdf
pdftohtml -c -f 1 -l 1 MCD.pdf
pdftohtml -c -f 1 -l 1 MCK.pdf
pdftohtml -c -f 1 -l 1 MDT.pdf
pdftohtml -c -f 1 -l 1 MRK.pdf
pdftohtml -c -f 1 -l 1 MET.pdf
pdftohtml -c -f 1 -l 1 MTD.pdf
pdftohtml -c -f 1 -l 1 MGM.pdf
pdftohtml -c -f 1 -l 1 KORS.pdf
pdftohtml -c -f 1 -l 1 MAA.pdf
pdftohtml -c -f 1 -l 1 MHK.pdf
pdftohtml -c -f 1 -l 1 TAP.pdf
pdftohtml -c -f 1 -l 1 MCO.pdf
pdftohtml -c -f 1 -l 1 MS.pdf
pdftohtml -c -f 1 -l 1 MOS.pdf
pdftohtml -c -f 1 -l 1 MSI.pdf
pdftohtml -c -f 1 -l 1 MSCI.pdf
pdftohtml -c -f 1 -l 1 NOV.pdf
pdftohtml -c -f 1 -l 1 NWL.pdf
pdftohtml -c -f 1 -l 1 NFX.pdf
pdftohtml -c -f 1 -l 1 NEM.pdf
pdftohtml -c -f 1 -l 1 NEE.pdf
pdftohtml -c -f 1 -l 1 NLSN.pdf
pdftohtml -c -f 1 -l 1 NKE.pdf
pdftohtml -c -f 1 -l 1 NI.pdf
pdftohtml -c -f 1 -l 1 NBL.pdf
pdftohtml -c -f 1 -l 1 JWN.pdf
pdftohtml -c -f 1 -l 1 NSC.pdf
pdftohtml -c -f 1 -l 1 NOC.pdf
pdftohtml -c -f 1 -l 1 NCLH.pdf
pdftohtml -c -f 1 -l 1 NRG.pdf
pdftohtml -c -f 1 -l 1 NUE.pdf
pdftohtml -c -f 1 -l 1 OXY.pdf
pdftohtml -c -f 1 -l 1 OMC.pdf
pdftohtml -c -f 1 -l 1 OKE.pdf
pdftohtml -c -f 1 -l 1 ORCL.pdf
pdftohtml -c -f 1 -l 1 PKG.pdf
pdftohtml -c -f 1 -l 1 PH.pdf
pdftohtml -c -f 1 -l 1 PNR.pdf
pdftohtml -c -f 1 -l 1 PKI.pdf
pdftohtml -c -f 1 -l 1 PRGO.pdf
pdftohtml -c -f 1 -l 1 PFE.pdf
pdftohtml -c -f 1 -l 1 PCG.pdf
pdftohtml -c -f 1 -l 1 PM.pdf
pdftohtml -c -f 1 -l 1 PSX.pdf
pdftohtml -c -f 1 -l 1 PNW.pdf
pdftohtml -c -f 1 -l 1 PXD.pdf
pdftohtml -c -f 1 -l 1 PNC.pdf
pdftohtml -c -f 1 -l 1 RL.pdf
pdftohtml -c -f 1 -l 1 PPG.pdf
pdftohtml -c -f 1 -l 1 PPL.pdf
pdftohtml -c -f 1 -l 1 PX.pdf
pdftohtml -c -f 1 -l 1 PG.pdf
pdftohtml -c -f 1 -l 1 PGR.pdf
pdftohtml -c -f 1 -l 1 PLD.pdf
pdftohtml -c -f 1 -l 1 PRU.pdf
pdftohtml -c -f 1 -l 1 PEG.pdf
pdftohtml -c -f 1 -l 1 PSA.pdf
pdftohtml -c -f 1 -l 1 PHM.pdf
pdftohtml -c -f 1 -l 1 PVH.pdf
pdftohtml -c -f 1 -l 1 PWR.pdf
pdftohtml -c -f 1 -l 1 DGX.pdf
pdftohtml -c -f 1 -l 1 RRC.pdf
pdftohtml -c -f 1 -l 1 RJF.pdf
pdftohtml -c -f 1 -l 1 RTN.pdf
pdftohtml -c -f 1 -l 1 O.pdf
pdftohtml -c -f 1 -l 1 RHT.pdf
pdftohtml -c -f 1 -l 1 REG.pdf
pdftohtml -c -f 1 -l 1 RF.pdf
pdftohtml -c -f 1 -l 1 RSG.pdf
pdftohtml -c -f 1 -l 1 RMD.pdf
pdftohtml -c -f 1 -l 1 RHI.pdf
pdftohtml -c -f 1 -l 1 ROK.pdf
pdftohtml -c -f 1 -l 1 COL.pdf
pdftohtml -c -f 1 -l 1 ROP.pdf
pdftohtml -c -f 1 -l 1 RCL.pdf
pdftohtml -c -f 1 -l 1 CRM.pdf
pdftohtml -c -f 1 -l 1 SCG.pdf
pdftohtml -c -f 1 -l 1 SLB.pdf
pdftohtml -c -f 1 -l 1 SEE.pdf
pdftohtml -c -f 1 -l 1 SRE.pdf
pdftohtml -c -f 1 -l 1 SHW.pdf
pdftohtml -c -f 1 -l 1 SPG.pdf
pdftohtml -c -f 1 -l 1 SLG.pdf
pdftohtml -c -f 1 -l 1 SNA.pdf
pdftohtml -c -f 1 -l 1 SO.pdf
pdftohtml -c -f 1 -l 1 LUV.pdf
pdftohtml -c -f 1 -l 1 SPGI.pdf
pdftohtml -c -f 1 -l 1 SWK.pdf
pdftohtml -c -f 1 -l 1 STT.pdf
pdftohtml -c -f 1 -l 1 SYK.pdf
pdftohtml -c -f 1 -l 1 STI.pdf
pdftohtml -c -f 1 -l 1 SYF.pdf
pdftohtml -c -f 1 -l 1 SYY.pdf
pdftohtml -c -f 1 -l 1 TPR.pdf
pdftohtml -c -f 1 -l 1 TGT.pdf
pdftohtml -c -f 1 -l 1 TEL.pdf
pdftohtml -c -f 1 -l 1 FTI.pdf
pdftohtml -c -f 1 -l 1 TXT.pdf
pdftohtml -c -f 1 -l 1 TMO.pdf
pdftohtml -c -f 1 -l 1 TIF.pdf
pdftohtml -c -f 1 -l 1 TWTR.pdf
pdftohtml -c -f 1 -l 1 TWX.pdf
pdftohtml -c -f 1 -l 1 TJX.pdf
pdftohtml -c -f 1 -l 1 TMK.pdf
pdftohtml -c -f 1 -l 1 TSS.pdf
pdftohtml -c -f 1 -l 1 TDG.pdf
pdftohtml -c -f 1 -l 1 TRV.pdf
pdftohtml -c -f 1 -l 1 TSN.pdf
pdftohtml -c -f 1 -l 1 UDR.pdf
pdftohtml -c -f 1 -l 1 USB.pdf
pdftohtml -c -f 1 -l 1 UAA.pdf
pdftohtml -c -f 1 -l 1 UA.pdf
pdftohtml -c -f 1 -l 1 UNP.pdf
pdftohtml -c -f 1 -l 1 UAL.pdf
pdftohtml -c -f 1 -l 1 UNH.pdf
pdftohtml -c -f 1 -l 1 UPS.pdf
pdftohtml -c -f 1 -l 1 URI.pdf
pdftohtml -c -f 1 -l 1 UTX.pdf
pdftohtml -c -f 1 -l 1 UHS.pdf
pdftohtml -c -f 1 -l 1 UNM.pdf
pdftohtml -c -f 1 -l 1 VFC.pdf
pdftohtml -c -f 1 -l 1 VLO.pdf
pdftohtml -c -f 1 -l 1 VAR.pdf
pdftohtml -c -f 1 -l 1 VTR.pdf
pdftohtml -c -f 1 -l 1 VZ.pdf
pdftohtml -c -f 1 -l 1 V.pdf
pdftohtml -c -f 1 -l 1 VNO.pdf
pdftohtml -c -f 1 -l 1 VMC.pdf
pdftohtml -c -f 1 -l 1 WMT.pdf
pdftohtml -c -f 1 -l 1 DIS.pdf
pdftohtml -c -f 1 -l 1 WM.pdf
pdftohtml -c -f 1 -l 1 WAT.pdf
pdftohtml -c -f 1 -l 1 WEC.pdf
pdftohtml -c -f 1 -l 1 WFC.pdf
pdftohtml -c -f 1 -l 1 WELL.pdf
pdftohtml -c -f 1 -l 1 WU.pdf
pdftohtml -c -f 1 -l 1 WRK.pdf
pdftohtml -c -f 1 -l 1 WY.pdf
pdftohtml -c -f 1 -l 1 WHR.pdf
pdftohtml -c -f 1 -l 1 WMB.pdf
pdftohtml -c -f 1 -l 1 XRX.pdf
pdftohtml -c -f 1 -l 1 XL.pdf
pdftohtml -c -f 1 -l 1 XYL.pdf
pdftohtml -c -f 1 -l 1 YUM.pdf
pdftohtml -c -f 1 -l 1 ZBH.pdf
pdftohtml -c -f 1 -l 1 ZTS.pdf

